services:
  grimoire-db:
    container_name: grimoire-db
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ${GRIMOIRE_DATA_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - grimoire-network

  grimoire-backend:
    container_name: grimoire-backend
    image: ghcr.io/kaiserdrake/grimoire-backend:latest
    restart: always
    ports:
      - '3002:3001'
    env_file:
      - .env
    volumes:
      - ${GRIMOIRE_DATA_PATH}/uploads:/data
    depends_on:
      - grimoire-db
    networks:
      - grimoire-network

  grimoire-frontend:
    container_name: grimoire-frontend
    image: ghcr.io/kaiserdrake/grimoire-frontend:latest
    env_file:
      - .env
    restart: always
    ports:
      - '8087:3000'
    depends_on:
      - grimoire-backend
    networks:
      - grimoire-network

networks:
  grimoire-network:
    driver: bridge
